In [1]:
from sklearn.mixture import GaussianMixture as GMM
from sklearn.datasets.samples_generator import make_blobs
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pickle

In [2]:
# reading the data

timit_df = pd.read_hdf("./train_features/mfcc/timit.hdf")
timit_df.head()

features labels
0  [7.078657420964836, -25.02194729819945, -6.325...    sil
1  [7.1665441896812405, -25.24814281113481, -1.60...    sil
2  [7.184905955583264, -28.73273351008029, -3.906...    sil
3  [7.034989672359181, -28.195340884727596, -3.54...    sil
4  [7.003780771426295, -28.139888943590634, -0.70...    sil

In [3]:
phone_names = timit_df['labels'].unique().tolist()#find unique values
print(phone_names)
phoneme_wise_list = []
#file = open('phoneme_name.txt', 'a+')
for i in range (len(phone_names)):
    phoneme_wise_list.append(timit_df[timit_df['labels']==phone_names[i]]) # seperating data phoneme wise
    #file.write(names[i]+",")



['sil', 'sh', 'ih', 'hh', 'eh', 'jh', 'd', 'ah', 'k', 's', 'uw', '', 'n', 'g', 'r', 'w', 'aa', 'dx', 'er', 'l', 'y', 'uh', 'ae', 'm', 'oy', 'dh', 'iy', 'v', 'f', 't', 'ow', 'ch', 'b', 'ng', 'ay', 'th', 'ey', 'p', 'aw', 'z']


## Training the GMM a) for MFCC (13), b) MFCC + Delta MFCC (26), c) MFCC + Delta + Delta-Delta and all the (a), (b), (c) i) with and ii) without energy coefficient (zeroeth coefficient and corresponding 14th coeff, and 27th coeff) - all for one size of GMM = 2

In [4]:
timit_df1 = pd.read_hdf("./train_features/mfcc_delta/timit.hdf")
timit_df2 = pd.read_hdf("./train_features/mfcc_delta_delta/timit.hdf")

phoneme_wise_list1 = []
phoneme_wise_list2 = []
for i in range (len(phone_names)):
    phoneme_wise_list1.append(timit_df1[timit_df1['labels']==phone_names[i]])

for i in range (len(phone_names)):
    phoneme_wise_list2.append(timit_df2[timit_df2['labels']==phone_names[i]])


### a) with i)

In [9]:
#creating 40 diffrent gmm for different phonemes
models=[]

for i in range (len(phoneme_wise_list)):
    features = np.array(phoneme_wise_list[i]["features"].tolist())
    models.append(GMM(n_components=2,covariance_type='diag').fit(features))
    path = "models//002_mfcc_withEC//"+phone_names[i]+".pkl"
    pickle.dump(models[i] , open(path, 'wb'))
    


### b) with i)

In [8]:
#creating 40 diffrent gmm for different phonemes
models=[]

for i in range (len(phoneme_wise_list1)):
    features = np.array(phoneme_wise_list1[i]["features"].tolist())
    models.append(GMM(n_components=2,covariance_type='diag').fit(features))
    path = "models//002_mfcc_delta_withEC//"+phone_names[i]+".pkl"
    pickle.dump(models[i] , open(path, 'wb'))


### c) with i)

In [10]:
#creating 40 diffrent gmm for different phonemes
models=[]

for i in range (len(phoneme_wise_list2)):
    features = np.array(phoneme_wise_list2[i]["features"].tolist())
    models.append(GMM(n_components=2,covariance_type='diag').fit(features))
    path = "models//002_mfcc_delta_delta_withEC//"+phone_names[i]+".pkl"
    pickle.dump(models[i] , open(path, 'wb'))


### a) with ii)

In [11]:
#creating 40 diffrent gmm for different phonemes
models=[]

for i in range (len(phoneme_wise_list)):
    features = np.array(phoneme_wise_list[i]["features"].tolist())
    features = features[:,1:]
    models.append(GMM(n_components=2,covariance_type='diag').fit(features))
    path = "models//002_mfcc//"+phone_names[i]+".pkl"
    pickle.dump(models[i] , open(path, 'wb'))


### b) with ii)

In [11]:
#creating 40 diffrent gmm for different phonemes
models=[]

for i in range (len(phoneme_wise_list1)):
    features = np.array(phoneme_wise_list1[i]["features"].tolist())
    temp1 = features[:,1:12]
    temp2 = features[:,14:25]
    features = np.hstack((temp1, temp2))
    #label = np.array(store[i]["labels"].unique().tolist())
    models.append(GMM(n_components=2,covariance_type='diag').fit(features))
    path = "models//002_mfcc_delta//"+phone_names[i]+".pkl"
    pickle.dump(models[i] , open(path, 'wb'))
    

### c) with ii)

In [13]:
#creating 40 diffrent gmm for different phonemes
models=[]

for i in range (len(phoneme_wise_list2)):
    features = np.array(phoneme_wise_list2[i]["features"].tolist())
    temp1 = features[:,1:12]
    temp2 = features[:,14:25]
    temp3 = features[:,27:38]
    features = np.hstack((temp1, temp2, temp3))
    #label = np.array(store[i]["labels"].unique().tolist())
    models.append(GMM(n_components=2,covariance_type='diag').fit(features))
    path = "models//002_mfcc_delta_delta//"+phone_names[i]+".pkl"
    pickle.dump(models[i] , open(path, 'wb'))


## Training the GMM with different number of mixtures only for Case (a) for MFCC (ii) without energy coefficients - (2, 4, 8, 16, 32, 64,128,256). For 2 already did above.

### mixture component : 4

In [17]:
#creating 40 diffrent gmm for different phonemes
models=[]

for i in range (len(phoneme_wise_list)):
    features = np.array(phoneme_wise_list[i]["features"].tolist())
    features = features[:,1:]
    models.append(GMM(n_components=4,covariance_type='diag').fit(features))
    path = "models//004//"+phone_names[i]+".pkl"
    pickle.dump(models[i] , open(path, 'wb'))
models[0].weights_

array([0.21274401, 0.1796321 , 0.29638121, 0.31124268])

### mixture component : 8

In [19]:
#creating 40 diffrent gmm for different phonemes
models =[]

for i in range (len(phoneme_wise_list)):
    features = np.array(phoneme_wise_list[i]["features"].tolist())
    features = features[:,1:]
    models.append(GMM(n_components=8,covariance_type='diag').fit(features))
    path = "models//008//"+phone_names[i]+".pkl"
    pickle.dump(models[i] , open(path, 'wb'))
models[0].weights_

array([0.14738474, 0.18062229, 0.10776701, 0.06766057, 0.23309269,
       0.04354412, 0.12702131, 0.09290727])

### mixture component : 16

In [22]:
#creating 40 diffrent gmm for different phonemes
models =[]

for i in range (len(phoneme_wise_list)):
    features = np.array(phoneme_wise_list[i]["features"].tolist())
    features = features[:,1:]
    models.append(GMM(n_components=16,covariance_type='diag').fit(features))
    path = "models//016//"+phone_names[i]+".pkl"
    pickle.dump(models[i] , open(path, 'wb'))
models[0].weights_

array([0.05148623, 0.08425272, 0.04899861, 0.05866363, 0.03874476,
       0.03612453, 0.06370626, 0.1464804 , 0.0536198 , 0.08888698,
       0.09526805, 0.03355841, 0.06354869, 0.06192713, 0.02635753,
       0.04837629])

### mixture component : 32

In [23]:
#creating 40 diffrent gmm for different phonemes
models =[]

for i in range (len(phoneme_wise_list)):
    features = np.array(phoneme_wise_list[i]["features"].tolist())
    features = features[:,1:]
    models.append(GMM(n_components=32,covariance_type='diag').fit(features))
    path = "models//032//"+phone_names[i]+".pkl"
    pickle.dump(models[i] , open(path, 'wb'))
models[0].weights_

array([0.04470096, 0.03862213, 0.04934954, 0.03353482, 0.01474038,
       0.03384174, 0.01544035, 0.03461123, 0.02586804, 0.01924646,
       0.02988094, 0.04262006, 0.01519346, 0.0466366 , 0.02351846,
       0.02957312, 0.01296083, 0.02698082, 0.0150077 , 0.03344873,
       0.02858623, 0.00681384, 0.02575541, 0.02739157, 0.0327493 ,
       0.07406895, 0.02053717, 0.04766103, 0.02632993, 0.0468092 ,
       0.0276443 , 0.04987671])

### mixture component :  64

In [25]:
#creating 40 diffrent gmm for different phonemes
models =[]

for i in range (len(phoneme_wise_list)):
    features = np.array(phoneme_wise_list[i]["features"].tolist())
    features = features[:,1:]
    models.append(GMM(n_components=64,covariance_type='diag').fit(features))
    path = "models//064//"+phone_names[i]+".pkl"
    pickle.dump(models[i] , open(path, 'wb'))
models[0].weights_

array([0.02077035, 0.03454446, 0.02923573, 0.0226325 , 0.00935513,
       0.00600882, 0.01880534, 0.03948364, 0.01423543, 0.03022642,
       0.01750583, 0.00664414, 0.01288382, 0.02448705, 0.0067563 ,
       0.01427434, 0.02271633, 0.00755569, 0.01270767, 0.01433372,
       0.01782577, 0.00361262, 0.01256615, 0.01262096, 0.02201846,
       0.01018496, 0.02064451, 0.01617888, 0.02060659, 0.02204358,
       0.01703198, 0.01649919, 0.01710358, 0.00753165, 0.00734402,
       0.01928949, 0.01071695, 0.00498488, 0.01136363, 0.00673497,
       0.01960876, 0.00895923, 0.00471328, 0.02149252, 0.00367673,
       0.02302356, 0.01667931, 0.01156769, 0.01357161, 0.02945956,
       0.00721997, 0.01290925, 0.01436295, 0.01494679, 0.01113387,
       0.01022191, 0.00357005, 0.01816778, 0.01574963, 0.00761695,
       0.01548601, 0.01747773, 0.01661054, 0.03970879])

### mixture component : 128

In [26]:
#creating 40 diffrent gmm for different phonemes
models =[]

for i in range (len(phoneme_wise_list)):
    features = np.array(phoneme_wise_list[i]["features"].tolist())
    features = features[:,1:]
    models.append(GMM(n_components=128,covariance_type='diag').fit(features))
    path = "models//128//"+phone_names[i]+".pkl"
    pickle.dump(models[i] , open(path, 'wb'))
models[0].weights_

array([0.0084934 , 0.00920839, 0.00879792, 0.01095725, 0.01002664,
       0.00463478, 0.00736503, 0.00205217, 0.00950587, 0.00644958,
       0.00323567, 0.00346256, 0.00610388, 0.01244467, 0.00391935,
       0.01204577, 0.01352495, 0.00808966, 0.01442885, 0.0033721 ,
       0.0252694 , 0.0078184 , 0.00311834, 0.00344258, 0.01119713,
       0.00250822, 0.00389911, 0.00330809, 0.00676563, 0.00357434,
       0.00732526, 0.00912822, 0.00811034, 0.00534894, 0.01001274,
       0.01728464, 0.00450137, 0.00331219, 0.01550178, 0.00353652,
       0.00595993, 0.00909362, 0.00717442, 0.00877928, 0.01313889,
       0.00573973, 0.0028576 , 0.00566799, 0.00967581, 0.0184491 ,
       0.01389938, 0.01355892, 0.00543721, 0.00581901, 0.00568286,
       0.01221258, 0.00771289, 0.00285645, 0.01101131, 0.01090031,
       0.00394112, 0.01527209, 0.00343885, 0.00465828, 0.0071383 ,
       0.00856357, 0.0048288 , 0.00523171, 0.006911  , 0.01106092,
       0.00862113, 0.00146754, 0.00656401, 0.00281414, 0.00824

### mixture component : 256

In [27]:
#creating 40 diffrent gmm for different phonemes
models =[]

for i in range (len(phoneme_wise_list)):
    features = np.array(phoneme_wise_list[i]["features"].tolist())
    features = features[:,1:]
    models.append(GMM(n_components=256,covariance_type='diag').fit(features))
    path = "models//256//"+phone_names[i]+".pkl"
    pickle.dump(models[i] , open(path, 'wb'))
models[0].weights_

array([0.00278751, 0.01171373, 0.00772138, 0.00946035, 0.00452782,
       0.01343315, 0.00109623, 0.00454664, 0.00567267, 0.00249324,
       0.0047108 , 0.00245254, 0.00222697, 0.00182964, 0.00409505,
       0.00625018, 0.00537388, 0.00435088, 0.00211449, 0.0067587 ,
       0.00430521, 0.00477272, 0.00198557, 0.00145955, 0.00269664,
       0.00262734, 0.0030558 , 0.00157375, 0.00180489, 0.00438453,
       0.00295047, 0.00614255, 0.0072621 , 0.00775981, 0.00637283,
       0.0039111 , 0.00404864, 0.0015058 , 0.0029019 , 0.00424184,
       0.01388828, 0.00463615, 0.00106698, 0.00394301, 0.00264216,
       0.00545745, 0.00367864, 0.0027781 , 0.00220251, 0.00343419,
       0.00408903, 0.00121668, 0.00338096, 0.0040665 , 0.00457781,
       0.0026857 , 0.00303785, 0.00481003, 0.00327816, 0.0030829 ,
       0.00366169, 0.00401562, 0.00124203, 0.00360524, 0.00686929,
       0.00130374, 0.00645326, 0.00451039, 0.00572758, 0.00480041,
       0.00603144, 0.0045752 , 0.00523089, 0.00745803, 0.00229